- name: init swarm
  command: docker swarm init
  ignore_errors: yes
  changed_when: False
- name: get join command
  shell: docker swarm join-token manager | grep -o 'docker swarm join --token.*'
  register: join_command
  changed_when: False
